[project]
name = "eventmanagementapi"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "django>=6.1.1",
    "django-ckeditor-5>=0.2.20",
    "django-cors-headers>=4.9.0",
    "django-storages[s3]>=1.14.6",
    "djangorestframework>=3.18.1",
    "djangorestframework-simplejwt>=5.5.1",
    "djangorestframework-stubs>=3.18.1",
    "gunicorn>=26.2.0",
    "pillow>=12.3.0",
    "psycopg[binary]>=3.3.5",
    "python-dotenv>=1.2.3",
    "ruff==0.16.8",
    "uvicorn>=0.53.0",
    "uvicorn-worker>=0.4.0",
    "whitenoise>=6.12.0",
]
