# Generated by Django 6.1.1 on 2026-09-14 08:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("start_at", models.DateTimeField()),
                ("end_at", models.DateTimeField()),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="events/%Y/%m/%d"
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=500)),
                ("meeting_url", models.URLField(blank=True)),
                ("is_online", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Registration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("name", models.CharField(max_length=200)),
                ("phone", models.CharField(max_length=20)),
                ("department", models.CharField(max_length=200)),
                ("course", models.CharField(max_length=200)),
                ("college", models.CharField(max_length=200)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="event_app.event",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CheckIn",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("check_in_at", models.DateTimeField(auto_now_add=True)),
                (
                    "registration",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="check_in",
                        to="event_app.registration",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="registration",
            constraint=models.UniqueConstraint(
                fields=("event", "email"), name="unique_event_registration"
            ),
        ),
    ]
