# Generated by Django 6.1.1 on 2026-09-14 09:05

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("event_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="description",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Description"),
        ),
    ]
