# Generated by Django 6.1.1 on 2026-09-14 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0002_alter_event_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkin',
            options={'ordering': ['-check_in_at']},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-start_at']},
        ),
        migrations.AlterModelOptions(
            name='registration',
            options={'ordering': ['-id']},
        ),
    ]
